### ISSUE TITLE
How to handle mvnd 1.x and mvnd 2.x?

### ISSUE THREAD

**Issue by cstamas** [mvndaemon/homebrew-mvnd#12]
Currently we have one formula `mvnd`. And mvnd 1.0.0 is out, but soon will come mvnd 2.0.0 as well.

How we want to handle this?

@ppalaga @gnodet

**Comment by gnodet** [comment]
Same as Maven ?

**Comment by cstamas** [comment]
Ok, here in maven Formula I see 3.9.8 only:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/maven.rb

So it means once mvnd 2.0.0 out, it will _replace_ mvnd 1.0.x (whatever version will be then current)?

**Comment by gnodet** [comment]
You can now install mvnd@1 to get the 1.x line.
Homebrew is mostly focusing on installing the latest version.  If you want to switch between versions, maybe using sdkman makes more sense.

**Comment by cstamas** [comment]
Updated README:
https://github.com/apache/maven-mvnd/commit/df1001824e65fcc673561233e8ec2c83949d0868

**Comment by paulochang** [comment]
Hi @gnodet , 
I disagree, according to the documentation homebrew should install the latest *stable* version. 
Beta versions should be tagged accordingly (https://docs.brew.sh/Acceptable-Casks#beta-unstable-development-nightly-or-legacy). Until a stable release of mvnd 2 is done, we should keep the version 1 as the main line.

My projects stopped running today because of some sort of incompatibility of mvnd 2 and I expect this to be the case for the majority of the users.

**Comment by JackPGreen** [comment]
> Until a stable release of mvnd 2 is done, IMHO we should keep the version 1 as the main line.
> {...}
> My projects stopped running today because of some sort of incompatibility with mvnd 2 and I expect this to be the case for the majority of the users.

I agree with this having been caught out in the same way.

More specifically, if you `brew install maven` you get [`Apache Maven 3.9.8`](https://formulae.brew.sh/formula/maven).
If you `brew install mvnd` you get `Apache Maven Daemon (mvnd) 2.0.0-beta-1 {...} Apache Maven 4.0.0-beta-3`

I would expect to be getting the same "latest" version of Maven, just with the daemon wrapper.

I had problems building a project with `mvnd` and initially thought it was a `mvnd` incompatibility until I realised the real problem was a new Maven version.

There are issues [like this](https://github.com/trustin/os-maven-plugin/pull/74) that mean _IMO_ Maven `v4` isn't ready to be a default choice yet.

**Comment by gnodet** [comment]
We do have 2 formulas since some time.

**Comment by paulochang** [comment]
So glad release/1.0.5 fixed the highlighted issues.
I have added a proposal to use `mvnd@2` as the formula for the release candidate of mvnd in line with the homebrew project guidelines. See https://github.com/mvndaemon/homebrew-mvnd/pull/20 

Will update the readme on https://github.com/apache/maven-mvnd if and when this PR is accepted.
